return {
  "ggandor/leap.nvim",
  enabled = false,
  opts = {
    keys = {
      { "S", mode = { "n", "x", "o" }, desc = "Leap in window" },
      { "gs", mode = { "n", "x", "o" }, desc = "Leap from windows" },
    },
    target_windows = { vim.fn.win_getid() },
    safe_labels = { "s", "e", "t", "n", "r", "o" },
    labels = {
      "s",
      "e",
      "t",
      "n",
      "r",
      "o",
      "p",
      "l",
      "f",
      "u",
      "d",
      "h",
      "c",
      ",",
      "g",
      "m",
      "w",
      "y",
    },
  },
}
